[package]
name = "rust-arduino"
version = "0.1.0"
authors = ["dark0ghost <dark0ghost@debian.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
