version: '3.3'

services:
  bot:
    build:
      context: .
      dockerfile:
        Dockerfile
    restart:
       on-failure
    volumes:
        - ".:/usr/src/app"

  database:
    image:
      postgres:9
    environment:
        POSTGRES_USER: tracker
        POSTGRES_PASSWORD: A3dSA24Dctf2v4HE
        PGDATA: ./postgres/data:/var/lib/postgresql/data/pgdata
    restart:
        always
    ports:
        - 5432:5432
    container_name: postgres

  adminer:
    image:
      adminer
    restart:
      always
    ports:
      - 8080:8080